### ISSUE TITLE
What is the size of the model?

### ISSUE THREAD

**Issue by zhang-can** [zhujiagang/DTPP#1]
hi, @zhujiagang ! Thanks for your excellent work!

I wonder what is the size of the DTPP-RGB & DTPP-Flow models on UCF101 & HMDB51 respectively?

**Comment by zhujiagang** [comment]
```
                 UCF101               HMDB51
DTPP-RGB         43066 kb              41666 kb

DTPP-Flow        43151 kb              41751 kb
```

The model size difference between UCF101 and HMDB51 is because of different number of classes.
And the difference between RGB and Flow models is because of different number of input channels.

**Comment by zhang-can** [comment]
Got it! Thanks a lot.
