### ISSUE TITLE
No module named 'pyparrots

### ISSUE THREAD

**Issue by WJShengD** [zhujiagang/DTPP#2]
in pyActionRecog, action_parrots.py has ''import pyparrots.dnn as dnn'', When I run, ‘’No module named 'pyparrots'‘’ appears.How do I get pyparrots?It would be my pleasure if you could answer for me.Thanks
PS：If you can speak Chinese, we can use Chinese to communicate.

**Comment by zhujiagang** [comment]
Hello, we'd better use English for other people's ease. 
Which command do you run before you get error?

**Comment by WJShengD** [comment]
OK，I didn't run any command，and I just ran a py file( pyActionRecog/action_parrots.py ).

**Comment by zhujiagang** [comment]
@WJShengD The python files of this repository are modified from TSN. It seems like pyActionRecog/action_parrots.py is not the part of running command. Just ignore it.

**Comment by WJShengD** [comment]
I see. Thank you very much.
